#!/usr/bin/env bash
# Run Nginx as Nginx

# Stop Nginx before making changes
service nginx stop

# Update Nginx configuration
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

# Start Nginx to apply changes
service nginx start
