#!/usr/bin/env bash
# Update package list and install nginx

sudo apt update && upgrade
sudo apt install nginx -y 
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
