#!/usr/bin/env bash
# Update package list and install nginx

sudo apt-get update

# Install nginx
sudo apt-get install nginx -y

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Holberton School" | sudo tee /etc/nginx/html/index.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
